services:
  api:
    restart: unless-stopped
    build: api
    network_mode: host
    environment:
      API_PORT: 8080
    devices:
      - /dev/lirc0
  shairport-sync:
    restart: unless-stopped
    build: shairport-sync-docker-curl
    network_mode: host
    devices:
      - /dev/snd
    environment:
      API_HOST: localhost
      API_PORT: 8080
      API_PATH: /volume
