services:
  api:
    restart: unless-stopped
    build: api
    network_mode: host
    environment:
      API_PORT: 8080
      UVICORN_LOG_LEVEL: warning
      API_LOG_LEVEL: info
    devices:
      - /dev/lirc0
  shairport-sync:
    restart: unless-stopped
    image: mikebrady/shairport-sync:4.3.7
    network_mode: host
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf:ro
    devices:
      - /dev/snd
