#!/usr/bin/env sh
set -e

HOST=${API_HOST:-localhost}
PORT=${API_PORT:-80}
PATH=${API_PATH_VOLUME:-/power}

set -x
/usr/bin/curl -s -X PUT $HOST:$PORT$PATH -H 'Content-Type: application/json' -d '{"power": "'$1'"}' > /dev/null
