#!/usr/bin/env sh
set -e

# env  # seems like env here is not the env we specify in docker-compose.yaml

HOST=${API_HOST:-localhost}
PORT=${API_PORT:-8080}
PATH=${API_PATH_VOLUME:-/power}

set -x
/usr/bin/curl -s -X PUT $HOST:$PORT$PATH -H 'Content-Type: application/json' -d '{"power": "'$1'"}' > /dev/null
