general =
{
	name = "Onkyo TX SV9041";
	ignore_volume_control = "yes";
}

alsa =
{
	output_device = "hw:0,0";
}

mqtt =
{
	enabled = "yes"; // Set this to yes to enable the mqtt-metadata-service.
	hostname = "homeassistant"; // Hostname of the MQTT Broker.
	port = 1883; // Port on the MQTT Broker to connect to.
	username = "shairport-sync"; // Set this to your MQTT user's username in order to enable username authentication.
	password = "shairport-sync"; // Set this to your MQTT user's password in order to enable username & password authentication.
	topic = "onkyo_tx_sv9041"; // MQTT topic where this instance of Shairport Sync should publish. If not set, the general.name value is used.
	publish_raw = "no"; // Whether to publish all available metadata under the codes given in the 'metadata' docs.
	publish_parsed = "yes"; // Whether to publish a small (but useful) subset of metadata under human-understandable topics.
	publish_cover = "no"; // Whether to publish the cover over MQTT in binary form. This may lead to a bit of load on the broker.
	enable_remote = "yes"; // Whether to remote control via MQTT. RC is available under `topic`/remote.
}

diagnostics =
{
	log_verbosity = 1;
}
