#!/usr/bin/env sh

HOST=${API_HOST:-localhost}
PORT=${API_PORT:-80}
PATH=${API_PATH_VOLUME:-/volume}

echo /usr/bin/curl -s -X PUT $HOST:$PORT$PATH -H 'Content-Type: application/json' -d '{"volume": '$1'}'
/usr/bin/curl -s -X PUT $HOST:$PORT$PATH -H 'Content-Type: application/json' -d '{"volume": '$1'}'
